on:
  push:
    branches:
      - 3.y
  pull_request:
    branches:
      - 3.y

name: 3.y - java 15 - tests
jobs:
  build:
    name: Run "tests"
    if: "!contains(github.event.head_commit.message, 'skipTests')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 3.y
        token: ${{ secrets.REPO_TOKEN }}

    - uses: joschi/setup-jdk@v2
      with:
        java-version: '15'
    
    - name: Run "mvn clean install"
      run: mvn clean install --settings hdes-build-parent/ci-maven-settings.xml
      env:
        CI: false
