on:
  push:
    branches:
      - 3.y

name: 3.y - java 17 - release
jobs:
  build:
    name: release branch 3.y
    if: "!startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 3.y
        token: ${{ secrets.REPO_TOKEN }}

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        gpg-private-key: ${{ secrets.GPG_KEY }}
        server-id: oss.sonatype.org
        gpg-passphrase: GPG_KEY_SEC
        server-username: OSSRH_USER
        server-password: OSSRH_PASS
    
    - name: Maven release
      run: ./hdes-build-parent/release.sh
      env:
        BOT_NAME: ${{ secrets.HDES_BOT_NAME }}
        BOT_EMAIL: ${{ secrets.HDES_BOT_EMAIL }}  
        BOT_TOKEN: ${{ secrets.HDES_BOT_TOKEN }}
        GPG_KEY_SEC:  ${{ secrets.HDES_GPG_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        
